run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: true

issues:
  exclude-use-default: false
